config/routes.rb
Rails.application.routes.draw do
  get 'page/index' => 'page#index'

  devise_for :users, :controllers => { registrations: 'users/registrations'}
  resources :posts, :path => 'entradas'
  resources :categories, :path => 'categorias'
  resources :images, :path => 'imagenes'
  root "posts#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "500", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content , presence: true
  belongs_to :user
  has_and_belongs_to_many :categories  
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_attached_file :cover, styles: { medium: "500", thumbnail: "200" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_attached_file :avatar, styles: { medium: "300x300" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  if Rails.env.production?
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :prepare_meta_tags, if: "request.get?"

  protect_from_forgery with: :exception

  before_action :set_posts
  before_action :set_author
  
  def prepare_meta_tags(options={})

    site_name   = "AlexeiDev"
    site        = "AlexeiDev"
    title       = "AlexeiDev - Aprende lo ultimo en tecnología"
    description = "Aprende lo último en tecnología y desarrollo, Ruby on rails, Python, Javascript, Android, ECMA 2015, CSS, HTML5"
    current_url = request.url

    defaults = {
      site:        site_name,
      title:       title,
      description: description,
      keywords:    %w[web software desarrollo moviles aplicaciones rails python ],
      twitter:     {site_name: site_name,
                    site: '@alexeidev',
                    card: 'resumen',
                    description: description
                    },
      og:          {url: current_url,
                    site_name: site_name,
                    title: title,
                    image: image_url('logo.png'),
                    description: description,
                    type: 'website'}    
    }
    options.reverse_merge!(defaults)
    set_meta_tags options
  end

  private

  def set_posts
    @postFeatured = Post.last(3)
  end
  def set_author
    @widgetAuthor = User.first
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update , :destroy]
  before_action :authenticate_user!, only: [:index, :new, :edit, :update , :destroy]
  before_action :no_index, only: [:index, :new, :edit]
  def index
    @categories = Category.all
    @page_title = 'Categorias'
  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new category_params
    if @category.save
      redirect_to categories_path, notice: "Bien, creaste una categoria"
    else
      render 'new', notice: "Opps, Ocurrio algun tipo de error"
    end
  end

  def edit
  end

  def show
    @posts = @category.posts.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
    @page_title = @category.name
  end

  def update
    if @category.update category_params
      redirect_to categories_path, notice: 'Se actualizo correctamente'
    else
      render 'new', notice: "Opps, Ocurrio algun tipo de error"
    end
  end
  def destroy
    @category.destroy
    redirect_to categories_path
  end
  private
  def category_params
    params.require(:category).permit(:name, :color)
  end

  def find_category
    @category = Category.friendly.find(params[:id])
  end
  def no_index
    set_meta_tags noindex: true
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_image, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]
  before_action :no_index
  def index
    @images = Image.all
  end
  def new 
    @image = Image.new
  end
  def create
    @image = Image.new image_params
    if @image.save
      redirect_to images_path, notice: "Bien se subio la imagen"
    else
      render 'new', notice: "Opps, ocurrio algun error"
    end
  end
  private
  def image_params
    params.require(:image).permit(:name,:image)
  end
  def find_image
    @image = Image.find(params[:id])
  end
  def no_index
    set_meta_tags noindex: true
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show,:edit, :destroy , :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]
  before_action :no_index, only: [:new, :edit]
  before_action :og_tags, only: [:show]
	def index
    @page_title = 'Blog de Tecnología y Desarrollo'
    @posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 5)
	end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to posts_path, notice: "Bien, se creó el Post"
    else
      render 'new', notice: "Opps, Ocurrio algun error revisa"
    end
  end

  def show
    @page_title = @post.title
  end
  def update
    params[:post][:category_ids] ||= []
    if @post.update post_params
      redirect_to @post, notice: 'Lo logramos, si se pudo actualizar'
    else
      redirect_to 'edit', notice: 'Algo salio Mál'
    end
  end
  def edit
    @categories = Category.all
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title,:content, :user, :cover, { category_ids:[] })
  end
  def find_post
    @post = Post.friendly.find(params[:id])
  end
  def no_index
    set_meta_tags noindex: true
  end
  def og_tags

    set_meta_tags og: {
      title:    @post.title,
      type:     'article',
      url:      post_url(@post),
      image:    URI.join(request.url, @post.cover.url(:thumbnail))
    }
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :facebook, :twitter, :instagram , :git ,:linkedin, :about)

  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :facebook, :twitter, :instagram , :git ,:linkedin, :about, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_idented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer,options).render(content).html_safe
  end
end

app/views/categories/_category.html.erb
<tr>
  <td> <%= category.id %> </td>
  <td> <%= link_to category.name, category_path(category) %></td>
  <td style="background: <%= category.color %>" > 
  </td>
  <td>
    <%= link_to edit_category_path(category) do %>
      <i class="fa fa-pencil-square"> </i>
    <% end %>
    <%= link_to category_path(category), method: :delete, data: { confirm: t('.sure')} do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
  </td>
</tr>
  

app/views/categories/_form.html.erb
<%= form_for @category, html: {class: 'pure-form pure-form-aligned'} do |f| %>
  <% if @category.errors.any? %>
    <h2><%= pluralize(@category.errors.count, "Error") %></h2>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="pure-control-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="pure-control-group">
    <%= f.label :color %>
    <%= f.color_field :color %>
  </div>
  <div class="pure-control">
    <%= f.submit class: 'pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h2> <%= t('.title') %> </h2>
<%= render 'form' %>

app/views/categories/index.html.erb
<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <td>#</td>
      <td><%= t('.name')%></td>
      <td><%= t('.color')%></td>
      <td><%= t('.actions')%></td>
    </tr>
  </thead>
  <tbody>
      <%= render @categories %>
  </tbody>
</table>

<%= link_to t('.new_link'), new_category_path %>

app/views/categories/new.html.erb
<h2> <%= t('.title') %> </h2>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2> Entradas en - <%= @category.name %> </h2>

<%= render @posts %>

<%= will_paginate @posts, :class => 'Pagination',:param_name => :page %>

app/views/images/_form.html.erb
<%= form_for @image , html: {class: 'pure-form pure-form-aligned', multipart: true} do |f| %>
  <% if @image.errors.any? %>
    <h2> <% pluralize(@image.errors.count, "Error")%></h2>
    <% @image.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  <% end %>

  <div class="pure-control-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="pure-control-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="pure-control">
    <%= f.submit class: 'pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/images/_image.html.erb
<%= image.name %>
<%= image_tag image.image.url(:medium) %> 
<%= asset_url(image.image.url(:medium)) %>    

app/views/images/index.html.erb
<h1>Imagenes</h1>
<%= render @images %>
<%= link_to t('newLink'), new_image_path %>

app/views/images/new.html.erb
<h2> Crear nueva imagen </h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags %>
  <meta name="google-site-verification" content="9VfZ1BcYtJAfXvXMFMXQOrjNdMmn8oDpfJEPpkPT-RI" />
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,400italic,500italic,500|Oswald:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/header' %>
  <%= render 'partials/postFeatured' %>
  <section class="MainLayout">
    <div class="MainLayout-posts wow slideInLeft" >
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% elsif alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'partials/sidebar' %>
  </section>
  <%= render 'partials/footer' %>
  <%= render 'partials/offCanvas' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render 'partials/disqus' %>
  <%= render 'partials/jsFacebook' %>
  <%= render 'partials/jsAnalytics' %>
</body>
</html>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/partials/_disqus.html.erb
<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'alexeidevcom';
/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
var s = document.createElement('script'); s.async = true;
s.type = 'text/javascript';
s.src = '//' + disqus_shortname + '.disqus.com/count.js';
(document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

app/views/partials/_footer.html.erb
<footer class="MainFooter">
  <div class="MainFooter-container">
    <div class="MainFooter-section">
      <div class="AboutMe">
        <h4 class="AboutMe-title"> Acerca de mí </h4>
        <div class="AboutMe-titleSeparator"> </div>
        <%= image_tag @widgetAuthor.avatar.url(:medium),class: 'AboutMe-photo' %>
        <p class="AboutMe-description"> <%= @widgetAuthor.about %> </p>
      </div>
    </div>
    <div class="MainFooter-section">
      <div class="WidgetSocial">
        <h4 class="WidgetSocial-title">
          Siguéme en
        </h4>
        <div class="WidgetSocial-titleSeparator"> </div>
        <div class="WidgetSocial-socialContent">
          <% if @widgetAuthor.facebook? %>
          <a href="<%= @widgetAuthor.facebook %>" target="_blank" class="WidgetSocial-facebook">
            <i class="fa fa-facebook-square"></i>
          </a>
          <% end %>
          <% if @widgetAuthor.twitter? %>
            <a href="<%= @widgetAuthor.twitter %>" target="_blank" class="WidgetSocial-twitter">
              <i class="fa fa-twitter-square"></i>
            </a>
          <% end %>
          <% if @widgetAuthor.instagram? %>
            <a href="<%= @widgetAuthor.instagram %>" target="_blank" class="WidgetSocial-instagram">
              <i class="fa fa-instagram"></i>
            </a>
          <% end %>
          <% if @widgetAuthor.git? %>
            <a href="<%= @widgetAuthor.git %>" target="_blank" class="WidgetSocial-gitlab">
              <i class="fa fa-git-square"></i>
            </a>
          <% end %>
          <% if @widgetAuthor.linkedin? %>
            <a href="<%= @widgetAuthor.linkedin %>" target="_blank" class="WidgetSocial-linkedin">
              <i class="fa fa-linkedin-square"></i>
            </a>
          <% end %> 
        </div>
      </div>
    </div>    
  </div>
</footer>
<div class="FooterCopyright">
  <p class="FooterCopyright-text"> 
    Copyright (c) 2015 - Creado para alexeidev.com
  </p>
</div>

app/views/partials/_header.html.erb
<header class="MainHeader wow bounceInDown">
  <div class="MainHeader-content">
    <div class="MainHeader-iconMenu">
      <i class="fa fa-bars"></i>
    </div>
    <div class="MainHeader-logo">
      <div class="Logo">
        <%= link_to root_path, class: "Logo-link" do %>
          <%= image_tag "logo.png", class: "Logo-image" %>
        <% end %>
      </div>
    </div>
    <div class="MainHeader-nav">
      <nav class="MainNav">
        <ul class="MainNav-list">
          <li class="MainNav-item">
            <%= link_to "Inicio", root_path, class: "MainNav-text" %>
          </li>
          <li class="MainNav-item">
            <a href="#" class="MainNav-text">
              Sobre Mi
            </a>
          </li>
          <li class="MainNav-item">
            <a href="#" class="MainNav-text">
              Cursos
            </a>
          </li>
          <li class="MainNav-item">
            <a href="#" class="MainNav-text">
              Educación
            </a>
          </li>
          <% if user_signed_in? %>
            <li class="MainNav-item">
              <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class => 'MainNav-text'  %>
            </li>
          <% end %>
        </ul>
      </nav>    
    </div>
    <div class="MainHeader-iconSearch">
       <i class="fa fa-search"></i>
    </div>  
  </div>  
</header>

app/views/partials/_jsAnalytics.html.erb
<% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-61269702-1', 'auto');
    ga('send', 'pageview');

  </script>
<% end %>

app/views/partials/_jsFacebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.4&appId=760193344109632";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/partials/_offCanvas.html.erb
<div class="MenuOffCanvas">
  <nav class="NavCanvas">
    <ul class="NavCanvas-list">
      <li class="NavCanvas-item">
        <%= link_to 'Inicio' , root_path, class: "NavCanvas-text" %>
      </li>
      <li class="NavCanvas-item">
        <a href="#" class="NavCanvas-text">
          Sobre Mi
        </a>
      </li>
      <li class="NavCanvas-item">
        <a href="#" class="NavCanvas-text">
          Cursos
        </a>
      </li>
      <li class="NavCanvas-item">
        <a href="#" class="NavCanvas-text">
          Educación
        </a>
      </li>
      <% if user_signed_in? %>
      <li class="NavCanvas-item">
        <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class => 'NavCanvas-text'  %>
      </li>
      <% end %>
    </ul>
    <div class="NavCanvas-buttonClose">
      <i class="fa fa-times"></i>
    </div>  
  </nav>
</div>

app/views/partials/_postFeatured.html.erb
<div class="Featured wow slideInLeft">
  <% @postFeatured.each do |post| %>
    <article class="PostFeatured">
      <% post.categories.each do |category| %>
        <%= link_to category_path(category), class: 'PostFeatured-stickerCategories' do %>
            <%= category.name %>      
        <% end %>
      <% end %>
    <%= image_tag post.cover.url(:medium), class: "PostFeatured-image" %> 
    <%= link_to '' ,post_path(post), class: 'PostFeatured-linkPost' %>
    </a>
    <div class="PostFeatured-container">
      <div class="PostFeatured-timePublised">
        <div class="PostFeatured-iconTime">
          <i class="fa fa-clock-o"></i>
        </div>
        <span class="PostFeatured-time">
          <%= distance_of_time_in_words_to_now(post.created_at) %>
        </span>
      </div>
      <a href="#" class="PostFeatured-linkTitle">
        <h3 class="PostFeatured-postTitle">
          <%= link_to post.title, post_path(post), class: 'PostFeatured-postTitleLink' %>
        </h3> 
      </a>
      <p class="PostFeatured-content">
        <%= truncate(strip_tags( markdown post.content ),length:150) %>
      </p>
      <div class="PostFeatured-button">
        <div class="Button">
          <%= link_to t('.more'), post_path(post), class: "Button-blue"  %>            
        </div>
      </div>
    </div>
  </article>
  <% end %>
</div>

app/views/partials/_sidebar.html.erb
<aside class="MainLayout-sidebar  wow slideInRight">
  <div class="Widget">
    <h5 class="Widget-title"> Siguenos en Facebook </h5>
    <div class="Widget-titleSeparator"> </div>
    <div class="Widget-content">
      <div class="fb-page" data-width="350" data-href="https://www.facebook.com/devalexei" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/devalexei"><a href="https://www.facebook.com/devalexei">Alexeidev.com</a></blockquote></div></div>
    </div>
  </div>
  <div class="Widget">
    <h5 class="Widget-title"> Publicidad </h5>
    <div class="Widget-titleSeparator"> </div>
    <div class="Widget-content">
      <div class="Ads">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- alexeidev -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:300px;height:250px"
             data-ad-client="ca-pub-8176036793735031"
             data-ad-slot="6455887681"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </div>
    </div>
  </div>
  <div class="Widget">
    <h5 class="Widget-title"> Más Popular </h5>
    <div class="Widget-titleSeparator"> </div>
    <div class="Widget-content">
      <% @postFeatured.each do |post| %>
        <article class="PopularArticle">
        <a href="<%= post_url(post)%>" class="PopularArticle-imageLink">
          <%= image_tag post.cover.url(:medium), class: "PopularArticle-image" %> 
        </a>
        <a href="" class="PopularArticle-title"> <%= post.title %></a>
      </article>
      <% end %>
    </div>
  </div>
</aside>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'alexeidevcom';
    var disqus_shortname = 'alexeidevcom';
    var disqus_identifier = '<%= @post.title %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= post_url(@post) %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_post.html.erb
<article class="Post">
  <h3 class="Post-title">
    <%= link_to post.title, post_path(post),class: 'Post-linkTitle' %>
  </h3>
  <%= render 'posts/postInformation', post: post  %>
  <div class="Post-featuredImage">
    <%= image_tag post.cover.url(:medium), class: "Post-image" %> 
  </div>
  <div class="Post-content">
    <div class="Post-text">
     <%= truncate(strip_tags( markdown post.content ),length:250) %>
    </div>
  </div>
  <div class="Post-innerContent">
    <div class="Post-buttonMore">
      <div class="Button">
        <%= link_to t('.readMore') , post_path(post), class: 'Button-more' %>
      </div>
    </div>
    <%= render 'posts/share', post: post  %> 
  </div>
</article>

app/views/posts/_postInformation.html.erb
<div class="Post-information">
  <div class="Post-itemInformation">
    <div class="Post-iconTime">
      <i class="fa fa-clock-o"></i>
    </div>
    <span class="Post-textInformation"> <%= distance_of_time_in_words_to_now(post.created_at) %> </span>
  </div>
  <div class="Post-itemInformation">
    <div class="Post-iconAuthor">
      <i class="fa fa-user"></i>
    </div>
    <span class="Post-textInformation"> <%= post.user.name %> </span>
  </div>
  <div class="Post-itemInformation">
    <div class="Post-iconCategory">
      <i class="fa fa-folder-o"></i>
    </div>
    <span class="Post-textInformation"> 
    <% post.categories.each do |category| %>
      <%= link_to category.name, category_path(category) %>
    <% end %>
    </span>
  </div>
  <div class="Post-itemInformation">
    <div class="Post-iconComment">
      <i class="fa fa-comments-o"></i>
    </div>
    <span class="Post-textInformation disqus-comment-count" data-disqus_identifier="<%= post.title %>" data-disqus-url="<%= post_url(post) %>"> </span>
  </div>
</div>

app/views/posts/edit.html.erb
<%- model_name = @post.class.model_name.human %>
<h3><%= t('.title', model: model_name) %></h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render @posts %>
<% if user_signed_in? %>
  <%= link_to t('.new_link'), new_post_path %>
<% end %>
<%= will_paginate @posts, :class => 'Pagination',:param_name => :page %>

app/views/posts/show.html.erb
<%- model_name = @post.class.model_name.human %>

<article class="Post">
  <% if user_signed_in? %>
    <%= link_to t('.edit', model: model_name ), edit_post_path %>
    <%= link_to t('.delete', model: model_name), post_path(@post), method: :delete, data: { confirm: t('.sure')} %>
  <% end %>
  <h3 class="Post-title">
    <%= @post.title%>
  </h3>
  <%= render 'posts/postInformation', post: @post %>
  <div class="Post-featuredImage">
    <%= image_tag @post.cover.url(:medium), class: "Post-image" %> 
  </div>
  <div class="Post-content">
    <div class="Post-text">
      <%= markdown @post.content %>
    </div>
  </div>
  <%= render 'posts/share', post: @post  %>
</article>
<div class="Author">
  <h4 class="Author-title">
    Acerca del autor
  </h4>
  <div class="Author-titleSeparator"> </div>
  <div class="Author-topContent">
    <%= image_tag @post.user.avatar.url(:medium), class: "Author-image" %> 
    <div class="Author-social">
      <div class="Author-socialContent">
        <% if @post.user.facebook? %>
          <a href="<%= @post.user.facebook %>" target="_blank" class="Author-facebook">
            <i class="fa fa-facebook-square"></i>
          </a>
        <% end %>
        <% if @post.user.twitter? %>
          <a href="<%= @post.user.twitter %>" target="_blank" class="Author-twitter">
            <i class="fa fa-twitter-square"></i>
          </a>
        <% end %>
        <% if @post.user.instagram? %>
          <a href="<%= @post.user.instagram %>" target="_blank" class="Author-instagram">
            <i class="fa fa-instagram"></i>
          </a>
        <% end %>
        <% if @post.user.git? %>
          <a href="<%= @post.user.git %>" target="_blank" class="Author-gitlab">
            <i class="fa fa-git-square"></i>
          </a>
        <% end %>
        <% if @post.user.linkedin? %>
          <a href="<%= @post.user.linkedin %>" target="_blank" class="Author-linkedin">
            <i class="fa fa-linkedin-square"></i>
          </a>
        <% end %>        
      </div>
    </div>
  </div>
  <div class="Author-bottomContent">
    <p class="Author-information">
      <%= @post.user.about %>
    </p>
  </div>
</div>
<div class="Comments">
  <h4 class="Comments-title">
    Comentarios
  </h4>
  <div class="Comments-titleSeparator"> </div>
    <div class="Comments-all">
      <%= render 'disqus' %>
    </div>
  </div>
</div>